#!/bin/bash
###COMENZAMOS CREANDO VARIABLES CON COLORES###
ROJO='\e[0;31m'
CYAN='\e[0;36m'
VERDE='\e[0;32m'
BLANCO='\e[1;37m'

#PASAMOS A MOSTRAR EL TEXTO CON COLORES.
#MUY IMPORTANTE HACER ECHO CON EL PARAMETRO -e
echo -e "${ROJO}Vamos ${CYAN}a probar ${VERDE}diferentes ${BLANCO}colores"